"""V1

Revision ID: 82c90d5a65d9
Revises: 
Create Date: 2025-12-06 07:25:35.867421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c90d5a65d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('max_instructor', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('max_teaching_assistant', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'max_teaching_assistant')
    op.drop_column('events', 'max_instructor')
    # ### end Alembic commands ###
