"""V2_add_max_instructor_and_max_teaching_assistant

Revision ID: 902159baef27
Revises: 82c90d5a65d9
Create Date: 2025-12-06 11:01:27.233847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '902159baef27'
down_revision: Union[str, Sequence[str], None] = '82c90d5a65d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
